# -*- coding: utf-8 -*-
# Generated by Django 1.9.6 on 2017-08-31 05:55
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('articles', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='article',
            name='img',
            field=models.CharField(default='', max_length=200),
        ),
        migrations.AddField(
            model_name='article',
            name='summary',
            field=models.TextField(default='', verbose_name='summary'),
        ),
    ]
